### ISSUE TITLE
Problem with the pakchunk-5 key for version 1.1

### ISSUE THREAD

**Issue by bfloat16** [ClostroOffi/wuwa-aes-archive#3]
It seems that the AES key in the README does not work for the CN client's pakchunk-5.
In the Client-Win64-Shipping.exe, only the master key can be found. How should the other two keys be located?

**Comment by ClostroOffi** [comment]
Hi! Keys in this repo are for Global version (& CN Beta) of the game.
Pakchunk-5 key is sent from the server. So you'll need a packet sniffer or something else to track received/sent packets while playing.

**Comment by bfloat16** [comment]
> Hi! Keys in this repo are for Global version (& CN Beta) of the game. Pakchunk-5 key is sent from the server. So you'll need a packet sniffer or something else to track received/sent packets while playing.

It seems like the key is issued under this link?，How can I decrypt it? (Or did I not find the right place?😑)
https://cdn-qiniu-cn-mc.aki-game.com/prod/client/??????/Windows/KeyList_1.1.0.json
