### ISSUE TITLE
 It seems wrong that the key pakchunk-5 for version 1.2

### ISSUE THREAD

**Issue by Long-Nicholas** [ClostroOffi/wuwa-aes-archive#7]
Hello, it seems that the key  pakchunk-5 for version 1.2 is error.

**Comment by ClostroOffi** [comment]
Hi there! I just checked if the key is correct, and I confirm that it is! Make sure you are using UE 4.26 or higher and that the key is in the 'pakchunk-5-WindowsNoEditor.pak' section in FModel to access its content!

![image](https://github.com/user-attachments/assets/6723a2db-1212-47c4-91d6-8efb3c04e006)
![image](https://github.com/user-attachments/assets/69187281-0c71-4e3a-9ef7-9f8dc0e9d231)
![image](https://github.com/user-attachments/assets/f14ee054-d600-4781-a0b0-27d10ad652d4)

**Comment by Long-Nicholas** [comment]
OK, I will try it again. thank you very much
