### ISSUE TITLE
Problem for unpack

### ISSUE THREAD

**Issue by Long-Nicholas** [ClostroOffi/wuwa-aes-archive#8]
Hello. I think I get a trouble with unpacking the file: pakchunk5

In fact, I usually use the tool  "UE_viewer" for unpacking. But in this way, the tool give me a warning: "your key isn't correct" and I see your reply. you seems use another tool for unpacking. could you please teach me for unpacking this file?

Thank you very much

![image](https://github.com/user-attachments/assets/b1f15f42-29a0-4ec1-8db1-099064d8ffca)
![image](https://github.com/user-attachments/assets/85520194-bab6-4e5e-974d-7d9405ee11d8)

**Comment by ClostroOffi** [comment]
Try using [FModel](https://fmodel.app/).

**Comment by Long-Nicholas** [comment]
> Try using [FModel](https://fmodel.app/).

Hi. I had used the Fmodel. And the result are the same(I can't unpack it).the version that I use were the UE4.28 and UE5.0. 

I will show you in the following screenshots, and thank you for you help :

![image](https://github.com/user-attachments/assets/ea29e174-746a-44d8-bdae-cc95fe4e195a)
![image](https://github.com/user-attachments/assets/f01c64ab-00a5-4375-928f-e7cdbaadd34a)

**Comment by Long-Nicholas** [comment]
> Try using [FModel](https://fmodel.app/).

by the way, I have found another problem ：

I also can't open the file pakchunk5 of the game v1.1 by using the key you provided. I don't know where are the problem. 

Do you think the problem is caused by the difference of CN client and Global client?

Thanks. 
Good days

**Comment by ClostroOffi** [comment]
Oh, so there's the problem.
CN keys aren't the same. You'll need to get them by yourself.

**Comment by Long-Nicholas** [comment]
But how can I get it?

**Comment by Long-Nicholas** [comment]
could you please teach me? I am new in this field

**Comment by xavo95** [comment]
@Long-Nicholas test with one of this depending on your version, I don't have CN version so you will be the ginnea pig to test them. if they work please let us know

> Extracting PakData CN 1.0.0 PK and contents
Key ID: 236b550a-25b2-4457-adee-5b71c2b190f9
Key: 030115e0b73d89503d64d89fa4ca4966c16fc3b366aee6a1be3954f5edd09661

> Extracting PakData CN 1.1.0 PK and contents
Key ID: f2e33f8e-3965-414b-a0f3-a59b6177bc0f
Key: c6f1a514cc58a88c1fe934e93dbd6e532ea5a00c2a2c9e4ae7774832bff0686d

> Extracting PakData CN 1.2.0 PK and contents
Key ID: f4a466f2-026c-4848-a274-c4a09938f527
Key: 1454a21fd285f51959af0164eebd8ae81d725bf499f13525539e7a1568f0e9d8

**Comment by ClostroOffi** [comment]
I can't help you as I'm not the person who extracts the keys from the server. 
Please check if this key works: 0x1454A21FD285F51959AF0164EEBD8AE81D725BF499F13525539E7A1568F0E9D8

**Comment by Long-Nicholas** [comment]
> I can't help you as I'm not the person who extracts the keys from the server. Please check if this key works: 0x1454A21FD285F51959AF0164EEBD8AE81D725BF499F13525539E7A1568F0E9D8



> @Long-Nicholas test with one of this depending on your version, I don't have CN version so you will be the ginnea pig to test them. if they work please let us know
> 
> > Extracting PakData CN 1.0.0 PK and contents
> > Key ID: 236b550a-25b2-4457-adee-5b71c2b190f9
> > Key: 030115e0b73d89503d64d89fa4ca4966c16fc3b366aee6a1be3954f5edd09661
> 
> > Extracting PakData CN 1.1.0 PK and contents
> > Key ID: f2e33f8e-3965-414b-a0f3-a59b6177bc0f
> > Key: c6f1a514cc58a88c1fe934e93dbd6e532ea5a00c2a2c9e4ae7774832bff0686d
> 
> > Extracting PakData CN 1.2.0 PK and contents
> > Key ID: f4a466f2-026c-4848-a274-c4a09938f527
> > Key: 1454a21fd285f51959af0164eebd8ae81d725bf499f13525539e7a1568f0e9d8


Hey, I' am very glad to tell you that: the key for v1.2.0 and v1.1.0 are right. I don't have the source package for v1.0.0. so I have no way to test the key you provided. 

Thanks again for your generous support

![image](https://github.com/user-attachments/assets/a61ce36a-4156-4f51-bee9-a386b0513ee9)
![image](https://github.com/user-attachments/assets/88882b47-7791-426b-8b83-ddf908393903)

**Comment by Long-Nicholas** [comment]
By the way, is there any teacher could tell me how to extracts the keys from the server?
